import { Network } from 'lucide-react';
import { Algorithm } from './types';

export const graphAlgorithms: Algorithm[] = [
  {
    id: 'bfs',
    name: 'Breadth-First Search',
    category: 'graph',
    description: 'Traverses an unweighted graph level by level from a start node.',
    icon: Network,
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    pseudocode: ['enqueue start', 'while queue not empty', 'dequeue node', 'visit unvisited neighbors'],
    implementation: `function bfs(graph, start) { /* ... */ }`,
    realWorldExamples: [{ title: 'Unweighted shortest path', description: 'Finds fewest-edge path.', industry: 'Networking' }],
  },
  {
    id: 'dfs',
    name: 'Depth-First Search',
    category: 'graph',
    description: 'Traverses an unweighted graph by exploring deep along each branch.',
    icon: Network,
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    pseudocode: ['push start', 'while stack not empty', 'pop node', 'visit unvisited neighbors'],
    implementation: `function dfs(graph, start) { /* ... */ }`,
    realWorldExamples: [{ title: 'Cycle detection', description: 'Useful for graph traversal and cycle checks.', industry: 'Systems' }],
  },
  {
    id: 'dijkstra',
    name: "Dijkstra's Algorithm",
    category: 'graph',
    description: 'Finds minimum-cost paths in weighted graphs with non-negative edges.',
    icon: Network,
    timeComplexity: { best: 'O(V^2)', average: 'O(E log V)', worst: 'O(E log V)' },
    spaceComplexity: 'O(V)',
    pseudocode: ['initialize distances', 'extract min-distance node', 'relax outgoing edges', 'repeat'],
    implementation: `function dijkstra(graph, start) { /* ... */ }`,
    realWorldExamples: [{ title: 'Route planning', description: 'Find cheapest path using edge costs.', industry: 'Navigation' }],
  },
  {
    id: 'astar',
    name: 'A* Search',
    category: 'graph',
    description: 'Heuristic shortest-path algorithm on weighted non-negative graphs.',
    icon: Network,
    timeComplexity: { best: 'O(E)', average: 'O(E log V)', worst: 'O(E log V)' },
    spaceComplexity: 'O(V)',
    pseudocode: ['open set = start', 'pick min f=g+h', 'relax neighbors', 'stop at goal'],
    implementation: `function astar(graph, start, goal) { /* ... */ }`,
    realWorldExamples: [{ title: 'Game AI pathfinding', description: 'Fast shortest paths with heuristic guidance.', industry: 'Gaming' }],
  },
];
